### ISSUE TITLE
Consider renaming to .js from .jsx

### ISSUE THREAD

**Issue by felixyr** [florianstahr/react-native-settings-components#7]
Cheers for the great work on this component.

The react native packager is unable to locate the **.jsx** files. I get the following error.

> The module `./divider/divider-short` could not be found from `./node_modules/react-native-settings-components/src/index.js`. Indeed, none of these files exist:

I know React Native doesn't support .jsx naturally and I have tried the below configuration but it didn't work either.

> // ./rn-cli.config.js

```
module.exports = {
  getSourceExts: () => [ 'jsx', 'mjs', 'js' ],
}
```

I will appreciate any guide on this.

**Comment by florianstahr** [comment]
@Kipko What version of React Native are you using? I have 0.57.2 and it works with this config

> ./rn-cli.config.js
```
module.exports = {
  resolver: {
    sourceExts: ['js', 'json', 'ts', 'tsx', 'jsx'],
  },
};
```

The config changed in RN 0.57 because of a newer version of the metro packager.
See here: [https://facebook.github.io/metro/docs/en/configuration#resolver-options](https://facebook.github.io/metro/docs/en/configuration#resolver-options)

I don't consider renaming all .jsx files to .js because it clearly shows what file contains jsx and what doesn't as the [AirBnB React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react) suggests.
